server:
  # 设定http监听端口
  port: 8088
  # 指定server绑定的地址
  address: 127.0.0.1
  # 设定session的超时时间
  sessionTimeout: 30
  # 设定应用的context-path
  contextPath: /

spring:

  datasource:
    # 指定driver的类名，默认从jdbc url中自动探测
    driverClassName: com.mysql.cj.jdbc.Driver
    # l指定JDBC URL
    url: jdbc:mysql://127.0.0.1:3306/toutiao?serverTimezone=UTC&useSSL=false
    # 指定数据源名
    name: toutiao
    # 指定数据库名
    username: root
    # 指定数据库密码
    password: root

  jpa:
    # 指定目标数据库
    database: mysql
    # 是否开启sql的log，默认为: false
    show_sql: true
    # 指定DDL mode (none, validate, update, create, create-drop). 当使用内嵌数据库时，默认是create-drop，否则为none.
    hibernate:
      ddl-auto: update
    #  指定数据库方言
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  redis:
    # 指定Redis server host，默认为: localhost
    host: 127.0.0.1
    # 指定redis服务端端口，默认: 6379
    port: 6379

  thymeleaf:
    # 指定模板的模式，具体查看StandardTemplateModeHandlers，默认为: HTML5
    mode: HTML5
    # 是否开启模板缓存，默认true
    cache: false

  messages:
    # 指定message的basename，多个以逗号分隔，如果不加包名的话，默认从classpath路径开始，默认: messages
    basename: classpath:/i18n/messages

#  security:
#    basic:
#      # 是否开启基本的鉴权，默认为true
#      enabled: false